### ISSUE TITLE
2-joint leg forward and backward movement by servos

### ISSUE THREAD

**Issue by KendallRey** [AiO-TSD/arduino-4-legged-robot#1]
## Description:
Make a code for forward and backward movement of 2-joint leg (with 3 servos) by transmitting controls from one controller to another.

## Variables
- Main Servo
  - horizontal
  - center / rest -> 90 degrees
- Sub Servo
  - vertical
  - center / rest -> 90 degrees `[TBC]`
- Foot Servo
  - vertical
  - center / rest -> 90 degrees `[TBC]`

## Todos:
- [x] - Generate movement variables using `Dual-Axis` analog module
- [x] - Send movements variables to another controller (NRFL01 module)
- [x] - Make the class properties customizable (with constructor)
- [x] - Make a custom `class ServoLeg`
- [x] - Main Servo movement ( reverse, loop )
- [x] - Sub Servo movement
- [x] - Foot Servo movement

## Acceptance Criteria:
- [ ] - 
- [ ] -
- [ ] -
- [ ] -
