### ISSUE TITLE
2-joint leg left and right movement by servos

### ISSUE THREAD

**Issue by KendallRey** [AiO-TSD/arduino-4-legged-robot#2]
## Description:
Make a code for left and right movement of 2-joint leg (with 3 servos) by transmitting controls from one controller to another.

## Variables
- Main Servo
  - horizontal
  - center / rest -> 90 degrees
- Sub Servo
  - vertical
  - center / rest -> 90 degrees `[TBC]`
- Foot Servo
  - vertical
  - center / rest -> 90 degrees `[TBC]`

## Todos:
- [ ] - Generate movement variables using `Dual-Axis` analog module
- [ ] - Send movements variables to another controller (NRFL01 module)
- [ ] - Main Servo movement ( reverse, loop )
- [ ] - Sub Servo movement
- [ ] - Foot Servo movement

## Acceptance Criteria:
- [ ] - 
- [ ] -
- [ ] -
- [ ] -
